# This is a basic workflow to help you get started with Actions

name: Github Actions Sample Run

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      fullname: Abhishek

    steps:
      - uses: actions/checkout@v2

      - name: Test Step 1
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          My name is $fullname,
          echo ,Test and deploy your project using Github Actions.
